package com.melvic.archia.interpreter

import com.melvic.archia.ast.*
import com.melvic.archia.ast.compound.BoolQuery
import com.melvic.archia.ast.leaf.*
import com.melvic.archia.output.*
import kotlin.reflect.KCallable

typealias Evaluation = Result<JsonValue>

fun Query.interpret(): Evaluation {
    val output = this.queryClause?.interpret() ?: missingField(this::query)

    return when (output) {
        is Failed -> output
        is Success<*> -> json {
            "query" to output.value()
        }.success()
    }
}

fun Clause.interpret(parent: JsonValue = json {}): Evaluation {
    val objectOrEmpty = if (parent is JsonObject) parent else json {}

    return when (this) {
        is TermQuery -> interpret(objectOrEmpty)
        is MatchQuery -> interpret(objectOrEmpty)
        is RangeQuery -> interpret(objectOrEmpty)
        is BoolQuery -> interpret(objectOrEmpty)
        else -> json {}.success()
    }
}

fun TermQuery.interpret(parent: JsonObject): Evaluation {
    val field = this.field ?: return missingField(this::field)
    if (field.value == null) return missingField(field::value)

    val termFieldOut = json {
        prop(field::value) { text(it) }
        prop(field::boost) { num(it) }
    }

    val termOut = parent { "term" to json { field.name to termFieldOut } }
    return termOut.success()
}

fun MatchQuery.interpret(parent: JsonObject): Evaluation {
    val field = this.field ?: return missingField(this::field)
    if (field.query == null) return missingField(field::query)

    val matchFieldOut = with(field) {
        json {
            prop(::query) {
                when (it) {
                    is AString -> text(it.value)
                    is ANumber -> num(it.value)
                    is ABoolean -> bool(it.value)
                    is ADate -> text(it.value.toString())
                    else  -> JsonNull
                }
            }
            prop(::analyzer) { text(it) }
            prop(::autoGeneratedSynonymsPhraseQuery) { bool(it) }
            prop(::fuzziness) {
                when (it) {
                    is Fuzziness._0 -> num(0)
                    is Fuzziness._1 -> num(1)
                    is Fuzziness._2 -> num(2)
                    is Fuzziness.Auto -> it.distances?.let { distances ->
                        val (low, high) = distances
                        text("AUTO:[$low],[$high]")
                    } ?: text("AUTO")
                }
            }
            prop(::maxExpansions) { num(it) }
            prop(::prefixLength) { num(it) }
            prop(::transpositions) { bool(it) }
            propEnum(::fuzzyRewrite)
            prop(::lenient) { bool(it) }
            propEnum(::operator)
            prop(::minimumShouldMatch) { it.interpret(this) }
            propEnum(::zeroTermsQuery)
        }
    }

    val matchOut = parent { "match" to json { field.name to matchFieldOut } }
    return matchOut.success()
}

fun RangeQuery.interpret(parent: JsonObject): Evaluation {
    val field = this.field ?: return missingField(this::field)

    val rangeFieldOut = with(field) {
        json {
            fun <R, C : KCallable<R>>propFieldParam(callable: C) {
                prop(callable) {
                    when (it) {
                        is ANumber -> num(it.value)
                        is DateFormat -> text(it.lowerName())
                        else -> JsonNull
                    }
                }
            }
            propFieldParam(::gt)
            propFieldParam(::gte)
            propFieldParam(::lt)
            propFieldParam(::lte)

            propEnum(::format)
            propEnum(::relation)
            prop(::timeZone) { text(it) }
            prop(::boost) { num(it) }
        }
    }

    val rangeOut = parent { "range" to json { field.name to rangeFieldOut }}
    return rangeOut.success()
}

fun BoolQuery.interpret(parent: JsonObject): Evaluation {
    val propsOut = json {
        propWithAlt(::_must, ::must) { it.interpret() }
        propWithAlt(::_should, ::should) { it.interpret() }
        propWithAlt(::_filter, ::filter) { it.interpret() }
        propWithAlt(::_mustNot, ::mustNot) { it.interpret() }
        prop(::minimumShouldMatch) { it.interpret(this) }
        prop(::boost) { num(it) }
    }
    val boolOut = parent { "bool" to propsOut }
    return boolOut.success()
}

fun MultiClause.interpret(): Evaluation {
    if (this.size == 1)
        return this[0].interpret()

    val result: JsonArray = jsonArray()

    for (clause in this) {
        val eval = clause.interpret()
        if (eval is Failed) return eval
        result.add(eval.value())
    }

    return result.success()
}

fun MinimumShouldMatch.interpret(parent: JsonObject): JsonValue {
    val msm: MinimumShouldMatch = this
    return with(parent) {
        fun interpretSimple(it: SimpleMSM): JsonValue = when (it) {
            is ANumber -> num(it.value)
            is Percent -> text("${it.value}%")
            else -> JsonNull
        }
        fun interpretMin(it: MinimumShouldMatch): JsonValue = when (it) {
            is SimpleMSM -> interpretSimple(it)
            is Combination -> text("${it.value}<${interpretSimple(it.simple)}")
            is Multiple -> array(it.values.map { i -> interpretMin(i) })
            else -> JsonNull
        }
        interpretMin(msm)
    }
}
