package com.melvic.archia.ast.fulltext

import com.melvic.archia.ast.*

class MultiMatchQuery : WithField<MultiMatchField>() {
    override fun getField(name: String): MultiMatchField {
        return MultiMatchField(name)
    }
}

class MultiMatchField(
    name: String,
    var query: String? = null,
    var fields: List<String>? = null,
    var tieBreaker: Double? = null,

    // best fields, most fields, phrase & prefix, cross fields, bool prefix
    var analyzer: Analyzer? = null,
    var boost: Boost? = null,
    var lenient: Boolean? = null,
    var zeroTermsQuery: ZeroTermsQuery? = null,

    // best fields, most fields, phrase & prefix, bool prefix
    var fuzziness: Fuzziness? = null,
    var maxExpansions: Int? = null,

    // best fields, most fields, cross fields, bool prefix
    var operator: Operator? = null,
    var minimumShouldMatch: MinimumShouldMatch? = null,

    // best fields, most fields, cross fields
    var cutoffFrequency: Double? = null,

    // best fields, most fields, bool prefix
    var prefixLength: Int? = null,
    var rewrite: Rewrite? = null,

    // best fields, bool prefix
    var autoGeneratedSynonymsPhraseQuery: Boolean? = null,
    var fuzzyTranspositions: Boolean? = null,

    // phrase & prefix
    var slop: Int? = null
) : Field(name)

enum class MultiMatchType {
    BEST_FIELDS, MOST_FIELDS, CROSS_FIELDS, PHRASE, PHRASE_PREFIX, BOOL_PREFIX
}