package com.melvic.archia.leaf

import com.melvic.archia.*
import java.util.*

data class Match(var field: MatchField? = null) : Clause() {
    /**
     * Constructs a match field from a string
     */
    operator fun String.invoke(init: Init<MatchField>) {
        field = MatchField(this).apply(init)
    }
}

data class MatchField(
    val name: String,
    var query: MatchQueryValue? = null,
    var analyzer: String? = null,
    var autoGeneratedSynonymsPhraseQuery: Boolean? = null,
    var fuzziness: Fuzziness? = null,
    var maxExpansions: Int? = null,
    var prefixLength: Int? = null,
    var transpositions: Boolean? = null,
    var fuzzyRewrite: Rewrite? = null,
    var lenient: Boolean? = null,
    var operator: FieldOperator? = null,
    var minimumShouldMatch: MinimumShouldMatch? = null,
    var zeroTermsQuery: ZeroTermsQuery? = null
) {
    fun text(value: String) = MatchQueryValue.Text(value)
    fun num(value: Number) = MatchQueryValue.Number(value)
    fun bool(value: Boolean) = MatchQueryValue.Boolean(value)
    fun date(value: Date) = MatchQueryValue.Date(value)
}

sealed class MatchQueryValue {
    data class Text(val value: String) : MatchQueryValue()
    data class Number(val value: kotlin.Number) : MatchQueryValue()
    data class Boolean(val value: kotlin.Boolean) : MatchQueryValue()
    data class Date(val value: java.util.Date) : MatchQueryValue()
}

enum class FieldOperator { OR, AND }
enum class ZeroTermsQuery { NONE, ALL }
